### ISSUE TITLE
Patternfly React Demo App boilerplate discussion

### ISSUE THREAD

**Issue by priley86** [patternfly/patternfly-react-demo-app#1]
Let's discuss what boilerplate and frameworks we'd like to use for the PF-React demo app. Please suggest what combinations you'd like to use and any additional frameworks we'll need in this demo app.

Boilerplate:
[Create-React-App](https://github.com/facebookincubator/create-react-app)

Type system:
[Typescript](https://www.typescriptlang.org/), [Flow](https://flow.org/)

Styles:
[Patternfly LESS](https://github.com/patternfly/patternfly) / [Patternfly SASS](https://github.com/patternfly/patternfly-sass)

Build system / module bundler:
[Webpack2](https://webpack.github.io/) + Babel

State Management:
[Redux](http://redux.js.org/), [Redux-Saga](https://github.com/redux-saga/redux-saga)

JS Extensions:
[Rx.JS](https://github.com/Reactive-Extensions/RxJS)

UI components:
[Patternfly-React](https://github.com/patternfly/patternfly-react), [Patternfly-Webcomponents](https://github.com/patternfly-webcomponents/patternfly-webcomponents/)

Some relevant issues on these topics from the PF-React repo: [#3](https://github.com/patternfly/patternfly-react/issues/3), [#6](https://github.com/patternfly/patternfly-react/issues/6)

**Comment by priley86** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10214041-174329626_2-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by priley86** [comment]
Why Typescript instead of Flow?
I chose to use Typescript instead of Flow after noticing that Typescript currently has a much better degree of support for many React and 3rd party libraries. A simple comparison on Github shows this:
https://github.com/flowtype/flow-typed/tree/master/definitions/npm
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types

This is also quite noticeable in the larger JS ecosystem now (take Redux Saga for example which includes Typescript definitions by default). 

It is also evident that many Red Hat teams are currently using Typescript and this should allow further collaboration internally. However, using a type system such as this imposes many restrictions on developer productivity (but this may be good for large teams). I support that Flow and ES6 will both be viable options as well for future demo apps, however Typescript is the most supported option today.

Does this mean that [patternfly-react](https://github.com/patternfly/patternfly-react) should use Typescript / type systems? Our current view is that type systems impose additional effort on our Patternfly contributors which is not necessary (and could be seen as detrimental to newcomers). It should be adequate enough to write es6 UI components in patternfly-react and import these into React applications (whether typed or non typed).

**Comment by ohadlevy** [comment]
:-1: for adding typescript by default, i think it should be a project decision and not forced here at all.
The same goes for any redux (and saga) related work can be used here, but should not be forced by pf-react itself.

thanks :)

**Comment by jtomasek** [comment]
Forms:
[redux-form](http://redux-form.com/6.8.0/)

> Redux-Saga, Rx.JS

Shouldn't we decide for one of those as IIUC both are used to handle side effects in React Apps?





> for adding typescript by default, i think it should be a project decision and not forced here at all.
> The same goes for any redux (and saga) related work can be used here, but should not be forced by pf-react itself.

IIUC demo app just demonstrates usage of patternfly-react. It does not force other consumers to use mentioned tools. patternfly-react should not put any restrictions on consumer apps in terms of chosen tooling.

At the same time demo app should showcase usage of patternfly-react with the most commont tooling in React applications.

**Comment by priley86** [comment]
@ohadlevy @jtomasek  i agree w/ this sentiment that Typescript/Redux/Saga should be considered on a project by project basis (as there is obviously overhead is going w/ those approaches). I only attempted to provide some core examples which might be good for a team considering a large scale application with a large number of contributors. This is where static analysis shines...

This demo can be seen as a single example of a patternfly-react consumer (as @jtomasek) was saying. I am happy to write an es6 demo in the future too (for smaller teams).

**Comment by benjaminapetersen** [comment]
Looks like the latest is es6? Just to update this discussion.

**Comment by priley86** [comment]
yup i think we can close this issue now...
