### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by dmiller9911** [patternfly/patternfly-react-demo-app#23]
Currently, the project is using `$npm_package_sassIncludes` for building css.  This does not work on windows since it accesses variable with `%npm_package_sassIncludes%`. Additionally `cp` is not supported by windows.  We will need to add something like https://www.npmjs.com/package/ncp for the copy image and font scripts.

**Comment by Mhbuur** [comment]
I managed to get around the `cp` issue by installing Cygwin and adding "C:\Cygwin64;C:\cygwin64\bin" to the environment variable "Path".

I had to rebuild Sass for Windows 64 bit (npm rebuild node-sass), which again required python, Windows 8.1 SDK and what not.

Now I'm stuck in the Build-CSS part: patternfly import references in App.scss does not resolve even though patternfly obviously is installed:
`  "status": 1,
  "file": "c:/test/patternfly demo/patternfly-react-demo-app/src/App.scss",
  "line": 11,
  "column": 1,
  "message": "File to import not found or unreadable: patternfly.\nParent style sheet: c:/test/patternfly demo/patternfly-react-demo-app/src/App.scss",
  "formatted": "Error: File to import not found or unreadable: patternfly.\n       Parent style shee
t: c:/test/patternfly demo/patternfly-react-demo-app/src/App.scss\n        on line 11 of src/A
pp.scss\n>> @import 'patternfly';\n   ^\n"`

**Comment by Mhbuur** [comment]
I found a workaround for the variable issue using [`cross-var`](https://www.npmjs.com/package/cross-var):
1. `npm i cross-var`
2. In `package.json` change:

`"build-css": "node-sass-chokidar src/App.scss --output-style compressed $npm_package_sassIncludes_src $npm_package_sassIncludes_patternfly $npm_package_sassIncludes_patternflyReact $npm_package_sassIncludes_bootstrap $npm_package_sassIncludes_fontAwesome -o src/css",`

to    

`"build-css": "cross-var \"node-sass-chokidar src/App.scss --output-style compressed $npm_package_sassIncludes_src $npm_package_sassIncludes_patternfly $npm_package_sassIncludes_patternflyReact $npm_package_sassIncludes_bootstrap $npm_package_sassIncludes_fontAwesome -o src/css\"",`

I had to run `yarn install` to fix some dependency issues that npm didn't take care of.
Things seem to go through without errors and I can run the demo app.

**Comment by jeff-phillips-18** [comment]
@Mhbuur Do you plan to put up a PR with these changes?

**Comment by Mhbuur** [comment]
@jeff-phillips-18 Yeah, I just want to see if anyone comments on the change. Perhaps @dmiller9911 could confirm the fix on his side. Also the Cygwin approach is not really a fix. Perhaps there is a copy method that works on all platforms?

**Comment by Mhbuur** [comment]
Fixed the cp copy issue by using ncp instead:
1. npm i ncp
2. In `package.json` change:

```
    "copy-fonts": "cp -r node_modules/patternfly/dist/fonts src/",
    "copy-img": "cp -r node_modules/patternfly/dist/img src/",
```

to
```
    "copy-fonts": "ncp node_modules/patternfly/dist/fonts src/fonts",
    "copy-img": "ncp node_modules/patternfly/dist/img src/img",
```

@jeff-phillips-18 PR is in.
