### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by jonatasfreitasv** [patternfly/patternfly-react-demo-app#26]
Failed to compile
./src/App.js
Module not found: Can't resolve './css/App.css' in '/home/anon/Projects/patternfly-react-demo-app/src'
This error occurred during the build time and cannot be dismissed.

**Comment by amarie401** [comment]
`npm install -g yarn` if you don't have yarn already installed, then use `yarn install` `yarn build` `yarn start`

@priley86 we should probably note somewhere to use yarn since this is the same issue I had.

**Comment by priley86** [comment]
yep! I agree. Let's update the README soon.

**Comment by shawndwells** [comment]
bump to update the README :)

**Comment by amarie401** [comment]
The README.md has been updated now 👍 
I'm going to go ahead and close this issue.
