### ISSUE TITLE
Build fails due to unresolved import

### ISSUE THREAD

**Issue by JameelB** [patternfly/patternfly-react-demo-app#33]
When running `yarn build` the following issue occurs: 

```
Failed to compile.

Module not found: Error: Can't resolve './routes' in '/home/jbriones/projects/patternfly-react-demo-app/src'
```

This is due to a typo for the `Routes.js` import path in [App.js](https://github.com/patternfly/patternfly-react-demo-app/blob/master/src/App.js#L18)

**Comment by priley86** [comment]
ok - yes, this is a typo. It should be renamed to `routes.js`. For some reason this was somehow lost. Do you want to send a PR? thanks...

**Comment by JameelB** [comment]
@priley86 Created a PR for this, mind taking a look? https://github.com/patternfly/patternfly-react-demo-app/pull/35

**Comment by JameelB** [comment]
Closing this issue as this has been resolved in https://github.com/patternfly/patternfly-react-demo-app/pull/35

**Comment by priley86** [comment]
thanks @JameelB 👍
