### ISSUE TITLE
PF3: File to import not found or unreadable: ~react-bootstrap-typeahead/css/Typeahead.

### ISSUE THREAD

**Issue by Mhbuur** [patternfly/patternfly-react-demo-app#47]
Just dumping this here if anyone else runs into build problems wtih latest PF3.

When trying to build css I got this error:

```
{
  "status": 1,
  "file": "[...]/node_modules/patternfly-react/dist/sass/_type-ahead-select.scss",
  "line": 1,
  "column": 1,
  "message": "File to import not found or unreadable: ~react-bootstrap-typeahead/css/Typeahead.",
  "formatted": "Error: File to import not found or unreadable: ~react-bootstrap-typeahead/css/Typeahead.\n        on line 1 of node_modules/patternfly-react/dist/sass/_type-ahead-select.scss\n        from line 13 of node_modules/patternfly-react/dist/sass/_patternfly-react.scss\n        from line 16 of src/App.scss\n>> @import '~react-bootstrap-typeahead/css/Typeahead';\n\n   ^\n"
}
```
it seems tilde imports are not supported directly. 

I installed node-sass-tilde-importer and added
the parameter "--importer=node_modules/node-sass-tilde-importer" to the buid-css script line in package.json:

"build-css": "node-sass-chokidar src/ --importer=node_modules/node-sass-tilde-importer --output-style compressed $npm_package_sassIncludes_src $npm_package_sassIncludes_patternfly $npm_package_sassIncludes_patternflyReact $npm_package_sassIncludes_bootstrap $npm_package_sassIncludes_fontAwesome -o src/",

**Comment by sharvit** [comment]
Thank you for the information @Mhbuur :+1: 

Nice to see you could workaround that using `node-sass`, I want to recommend you to use webpack to build your css as you will get more features (like the tilde) and I believe it can simplify your work to a single `webpack.config.js` with the build config.
